// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWedding;

namespace MyWedding.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190604092042_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("MyWedding.Models.Guest", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Approved");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<bool?>("IsAttending");

                    b.Property<string>("Message")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.Property<DateTime>("dateAdded");

                    b.Property<DateTime>("dateUpdated");

                    b.Property<string>("mobile");

                    b.HasKey("id");

                    b.ToTable("guests");
                });
#pragma warning restore 612, 618
        }
    }
}
